name: KrakenD Configuration Deployment

on:
  push:
    branches: [main]
  pull_request:

jobs:
  krakend_check_and_deploy:
    runs-on: ubuntu-latest
    environment: flexible
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p tmp

      - name: Run KrakenD check
        run: |
          # make sure tmp is writable
          mkdir -p tmp
          chmod 777 tmp

          docker run --rm \
            --user root \
            -v "${GITHUB_WORKSPACE}:/etc/krakend" \
            -w /etc/krakend \
            -e FC_ENABLE=1 \
            -e FC_SETTINGS=config/settings/prod \
            -e FC_PARTIALS=config/partials \
            -e FC_TEMPLATES=config/templates \
            -e FC_OUT=/etc/krakend/tmp/out.json \
            -e SERVICE_NAME="KrakenD API Gateway" \
            krakend:latest check -tdc "krakend.tmpl"

      - name: Upload output file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: krakend-out
          path: tmp/out.json
          
      # Deploy to Kubernetes if on main branch and not a pull request
      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # skip if no kubeconfig secret
          if [ -z "${{ secrets.KUBE_CONFIG }}" ]; then
            echo "KUBE_CONFIG secret is empty – skipping deploy"
            exit 0
          fi

          # download kubectl
          curl -Lo kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/

          # load kubeconfig
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=./kubeconfig

           kubectl create configmap krakend-config \
            --from-file=tmp/out.json -n krakend \
            --dry-run=client -o yaml | \
          kubectl apply -f - --validate=false

          # restart gateway (no more kubectl cp)
          POD=$(kubectl get pod -n krakend -l app=krakend -o jsonpath='{.items[0].metadata.name}')
          kubectl cp tmp/out.json krakend/$POD:/etc/krakend/
          kubectl rollout restart deployment/krakend -n krakend
          kubectl rollout status deployment/krakend -n krakend

          # cleanup
          rm -f kubeconfig